destination: ./_site
auto:        true
lsi:         false
server:      false
server_port: 4000
pygments:    true
markdown:    maruku
permalink:   date
maruku:
  use_tex:    false
  use_divs:   false
  png_dir:    images/latex
  png_url:    /images/latex
headline:    thoughts which have made it into written existence
url:         unwiredcouch.com
domain:      unwiredcouch.com
